### ISSUE TITLE
Advance Post do not generate any record

### ISSUE THREAD

**Issue by gfaggioni** [EkoJr/wp-advanced-post-list#38]
I've installed Advanced post plugin and Event Manager (Event registration and booking management for WordPress. Recurring events, locations, google maps, rss, ical, booking registration and more!
Version 5.5.3.1 | Di Marcus Sykes).
Event manager allow a new post tassonomy called event. I setup a rule to show Event postings, ma the result is that no event is taken into account by advanced post ... any suggestion?

**Comment by EkoJr** [comment]
Unfortunately, I can't provide much support with other plugins, but I'm also having a hard time understanding the question.
